/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallergui_q1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author James Josue Molina
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ArrayList<Persona> personas = new ArrayList();
    private float x, y;
    private String lugar;
    
    private void cargarTabla(){
        DefaultTableModel modelo = (DefaultTableModel)jtable_persona.getModel();
        modelo.setRowCount(0);
        for (Persona persona : personas) {
            Object[] row = {persona.getTipo(), persona.getUser(), persona.getNombre(), persona.getCorreo(), persona.getLugar(), persona.getX(), persona.getY()};
            modelo.addRow(row);
        }
    }
    
    public void setCoordenada(float _x, float _y, String _lugar){
        x = _x;
        y = _y;
        lugar = _lugar;
        actualizar();
    }
    
    private void actualizar(){
        tb_lugar.setText(lugar);
        tb_x.setText(Float.toString(x));
        tb_y.setText(Float.toString(y));
    }
    
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        personas.add(new Persona("Serlio","Giron","serlio.giron@unitec.edu","Alumno","UNITEC",100,200));
        personas.add(new Persona("Juan","Mendez","juancarlosmendez21@unitec.edu","Profesor","CEUTEC",200,350));
        
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_persona = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_persona = new javax.swing.JTable();
        btn_pasar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tb_user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tb_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tb_correo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tb_lugar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tb_x = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tb_y = new javax.swing.JTextField();
        cb_tipo = new javax.swing.JComboBox<>();
        btn_guardar = new javax.swing.JButton();
        btn_mapa = new javax.swing.JButton();
        btn_guardarTxt = new javax.swing.JButton();
        btn_cargar = new javax.swing.JButton();
        btn_correo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personas");
        jt_persona.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_persona);

        jtable_persona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "User", "Nombre", "Correo", "Lugar", "X", "Y"
            }
        ));
        jScrollPane2.setViewportView(jtable_persona);

        btn_pasar.setText("<");
        btn_pasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pasarActionPerformed(evt);
            }
        });

        jLabel1.setText("User");

        jLabel2.setText("Nombre");

        jLabel3.setText("Correo");

        jLabel4.setText("Lugar");

        tb_lugar.setEnabled(false);

        jLabel5.setText("X");

        tb_x.setEnabled(false);

        jLabel6.setText("Y");

        tb_y.setEnabled(false);

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Profesor", "Jugador", "Instructor", "Chofer", "Director" }));

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_mapa.setText("Mapa");
        btn_mapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mapaActionPerformed(evt);
            }
        });

        btn_guardarTxt.setText("Guardar");
        btn_guardarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarTxtActionPerformed(evt);
            }
        });

        btn_cargar.setText("Cargar");
        btn_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarActionPerformed(evt);
            }
        });

        btn_correo.setText("Correo");
        btn_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_correoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pasar)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tb_correo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(tb_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tb_user, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(tb_lugar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(tb_x)
                                .addComponent(jLabel6)
                                .addComponent(tb_y))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb_tipo, 0, 118, Short.MAX_VALUE)
                                .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_guardarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_mapa)
                            .addComponent(btn_guardarTxt)
                            .addComponent(btn_cargar)
                            .addComponent(btn_correo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tb_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_guardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tb_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btn_pasar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mapaActionPerformed
        Mapa.execute(this);
    }//GEN-LAST:event_btn_mapaActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        String user = tb_user.getText();
        String correo = tb_correo.getText();
        String nombre = tb_nombre.getText();
        float xF = Float.parseFloat(tb_x.getText());
        float yF = Float.parseFloat(tb_y.getText());
        String lugarStr = tb_lugar.getText();
        String tipo = (String)cb_tipo.getSelectedItem();
        
        
        if(usuarioRepetido(user)){
            personas.add(new Persona(user,nombre,correo,tipo,lugarStr,xF, yF));
            JOptionPane.showMessageDialog(this,"Agregado exitosamente");
            tb_user.setText("");
            tb_correo.setText("");
            tb_nombre.setText("");
            tb_x.setText("");
            tb_y.setText("");
            tb_lugar.setText("");
            cb_tipo.setSelectedIndex(0);
            cargarTabla();
        }else{
            JOptionPane.showMessageDialog(this,"Usuario repetido");
        }
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_pasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pasarActionPerformed
        DefaultTreeModel modelo = (DefaultTreeModel)jt_persona.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)modelo.getRoot();
        
        String tipo = (String)jtable_persona.getValueAt(jtable_persona.getSelectedRow(), 0);
        
        String usuario = (String)jtable_persona.getValueAt(jtable_persona.getSelectedRow(), 1);
        
        int indice = -1;
        for (int i = 0; i < root.getChildCount(); i++)
            if(root.getChildAt(i).toString().equals(tipo)){
                indice = i;
                break;
            }
        
        if(indice > -1){
            //Agregarlo a ese nodo
            DefaultMutableTreeNode tipoNodo = (DefaultMutableTreeNode)root.getChildAt(indice);
            tipoNodo.add(new DefaultMutableTreeNode(usuario));
        }else{
            //Crear ese nodo
            DefaultMutableTreeNode tipoNodo = new DefaultMutableTreeNode(tipo);
            tipoNodo.add(new DefaultMutableTreeNode(usuario));
            root.add(tipoNodo);
        }
        modelo.reload();
    }//GEN-LAST:event_btn_pasarActionPerformed

    private void btn_guardarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarTxtActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int resultado = chooser.showSaveDialog(this);
            
            if(resultado == chooser.APPROVE_OPTION){
                String file = (String)JOptionPane.showInputDialog("Nombre del archivo");
                
                BufferedWriter bw = new BufferedWriter(new FileWriter(chooser.getSelectedFile()+"/"+file+".txt"));
                for (Persona persona : personas)
                    bw.write(persona.getTipo()+","+persona.getUser()+","+persona.getNombre()+","+persona.getCorreo()+","+persona.getLugar()+","+persona.getX()+","+persona.getY()+"\n");
                bw.close();
                JOptionPane.showMessageDialog(this,"Guardado exitosamente");
                
            }else{
                JOptionPane.showMessageDialog(this,"Cancelado");
            }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_guardarTxtActionPerformed

    private void btn_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int resultado = chooser.showSaveDialog(this);
            
            if(resultado == chooser.APPROVE_OPTION){
                BufferedReader br = new BufferedReader(new FileReader(chooser.getSelectedFile()));
                String line = "";
                while((line = br.readLine())!= null){
                    String[] campos = line.split(",");
                    personas.add(new Persona(campos[1],campos[2],campos[3],campos[0],campos[4], Float.parseFloat(campos[5]),Float.parseFloat(campos[6])));
                }
                cargarTabla();
                JOptionPane.showMessageDialog(this,"Cargado exitosamente");
            }else{
                JOptionPane.showMessageDialog(this,"Cancelado");
            }
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_btn_cargarActionPerformed

    private void btn_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_correoActionPerformed
        //shuwwymhojfprkdr
        Properties propiedades = new Properties();
        propiedades.setProperty("mail.smtp.host","smtp.gmail.com");
        propiedades.setProperty("mail.smtp.starttls.enable", "true");
        propiedades.setProperty("mail.smtp.port", "587");
        propiedades.setProperty("mail.smtp.auth","true");
        
        Session sesion = Session.getDefaultInstance(propiedades);
        String correoEnvia = "jjmolinaf12@gmail.com";
        String contrasena = "shuwwymhojfprkdr";
        String receptor = (String)jtable_persona.getValueAt(jtable_persona.getSelectedRow(), 3);
        String asunto = (String)JOptionPane.showInputDialog("Asunto");
        String mensaje = (String)JOptionPane.showInputDialog("Mensaje");
        try{
            MimeMessage mail = new MimeMessage(sesion);
            
            mail.setFrom(new InternetAddress(correoEnvia));
            mail.addRecipient(Message.RecipientType.TO, new InternetAddress(receptor));
            mail.setSubject(asunto);
            mail.setText(mensaje);
            
            Transport transporte = sesion.getTransport("smtp");
            transporte.connect(correoEnvia,contrasena);
            
            transporte.sendMessage(mail, mail.getRecipients(Message.RecipientType.TO));
            transporte.close();
            JOptionPane.showMessageDialog(this,"Listo! Revise el correo");
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_btn_correoActionPerformed

    
    private boolean usuarioRepetido(String usuario){
//        for (Persona persona : personas)
//            if(persona.getUser().equals(usuario))
//                return true;
//        return false;
        
        return personas.stream().filter(p -> p.getUser().equals(usuario)).count() < 1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cargar;
    private javax.swing.JButton btn_correo;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardarTxt;
    private javax.swing.JButton btn_mapa;
    private javax.swing.JButton btn_pasar;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jt_persona;
    private javax.swing.JTable jtable_persona;
    private javax.swing.JTextField tb_correo;
    private javax.swing.JTextField tb_lugar;
    private javax.swing.JTextField tb_nombre;
    private javax.swing.JTextField tb_user;
    private javax.swing.JTextField tb_x;
    private javax.swing.JTextField tb_y;
    // End of variables declaration//GEN-END:variables
}
